### ISSUE TITLE
How can I lint .cjsx files

### ISSUE THREAD

**Issue by soyjavi** [SublimeLinter/SublimeLinter-coffeelint#25]
Hi,

I'm trying to lint my `.cjsx` files (CoffeeScript JSX Syntax) but I don't know how can I configure sublimelinter for check those files

can you help me?

**Comment by joshmfrankel** [comment]
Looks like we should be able to add this functionality into the linter via "You may configure coffeelint’s behavior using coffeelint.json configuration files, exactly as is described in the coffeelint documentation." I additionally, found this concerning coffeelint.json files https://github.com/clutchski/coffeelint/blob/master/doc/user.md#how-do-i-use-jsx-reactjs. You'll probably need to additionally pass into your SublimeLinter User Settings for coffeelint the config path name into the args:

**Comment by braver** [comment]
There are two possible methods:

- Use a coffeelint.json configuration file. I'm not sure what the configuration allows there, but I'm sure it has documentation. This is the preferred method, because it will allow coffeelint to lint your files outside SublimeLinter too.
- Map the syntax to `coffeescript` using the [syntax_map setting](http://www.sublimelinter.com/en/latest/global_settings.html#syntax-map).
